import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Library,TerminalSquare,Image,ShieldCheck,Network,Workflow,RadioTower,GitCompareArrows,Search,Copy,ExternalLink,ChevronRight,Menu,X,BookOpen,Activity,Layers3} from 'lucide-react';
import './styles.css';

const sections=[
 {title:'',items:[['Dashboard','dashboard',LayoutDashboard]]},
 {title:'COMMANDS',items:[['Command Library','library',Library],['Command Studio','command-studio',TerminalSquare],['Command Visualiser','visualiser',Image]]},
 {title:'EXPLORERS',items:[['PrivEsc Explorer','privesc',ShieldCheck],['ATT&CK Explorer','attack',Network],['Attack Path Explorer','attack-path',GitCompareArrows]]},
 {title:'BUILDERS',items:[['Workflow Builder','workflow',Workflow]]},
 {title:'DEFENCE',items:[['Detection & Telemetry','detection',RadioTower],['Purple Team Mapping','purple',Layers3]]}
];
const commands=[
 {id:'applocker',title:'Inspect Effective AppLocker Policy',platform:'Windows',tool:'PowerShell',category:'Application Control',cmd:'Get-AppLockerPolicy -Effective -Xml',desc:'Retrieve the effective AppLocker policy applied to the current system.',tags:['AppLocker','Policy','Read-only']},
 {id:'clm',title:'Check PowerShell Language Mode',platform:'Windows',tool:'PowerShell',category:'PowerShell',cmd:'$ExecutionContext.SessionState.LanguageMode',desc:'Display the current PowerShell language mode.',tags:['CLM','PowerShell','Discovery']},
 {id:'listeners',title:'List Listening TCP Ports',platform:'Windows',tool:'PowerShell',category:'Network',cmd:'Get-NetTCPConnection -State Listen',desc:'List TCP endpoints currently listening on the host.',tags:['Network','Telemetry','TCP']},
 {id:'nmap',title:'Service Version Discovery',platform:'Linux',tool:'Nmap',category:'Network',cmd:'nmap -sV <TARGET>',desc:'Perform service version detection against an authorised target.',tags:['Nmap','Services','Recon']}
];
const cards={
 privesc:{title:'PrivEsc Explorer',desc:'Navigate privilege-escalation checks by platform, context and control boundary.',icon:ShieldCheck,items:['Windows posture','Linux posture','Writable locations','Service and task context','Application controls']},
 attack:{title:'ATT&CK Explorer',desc:'Browse techniques and connect them to commands, notes and defensive telemetry.',icon:Network,items:['Tactics','Techniques','Command mappings','Detection mappings','Related notes']},
 'attack-path':{title:'Attack Path Explorer',desc:'Build visual relationships between identities, systems, permissions and security boundaries.',icon:GitCompareArrows,items:['Identity nodes','Permission edges','Host relationships','Control boundaries','Linked notes']},
 workflow:{title:'Workflow Builder',desc:'Arrange assessment steps into reusable, visual security workflows.',icon:Workflow,items:['Add command','Add decision','Link notes','Add evidence point','Export workflow']},
 detection:{title:'Detection & Telemetry',desc:'See which telemetry sources can observe assessment activity and where detection coverage exists.',icon:RadioTower,items:['Process telemetry','PowerShell logging','Windows events','Network telemetry','EDR visibility']},
 purple:{title:'Purple Team Mapping',desc:'Connect offensive validation, defensive visibility, detections and learning outcomes.',icon:Layers3,items:['Technique','Validation action','Telemetry','Detection','Outcome']}
};
function App(){
 const [page,setPage]=useState('dashboard'); const [q,setQ]=useState(''); const [selected,setSelected]=useState(commands[0]); const [mobile,setMobile]=useState(false);
 const filtered=useMemo(()=>commands.filter(c=>`${c.title} ${c.platform} ${c.tool} ${c.category} ${c.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase())),[q]);
 const go=p=>{setPage(p);setMobile(false)};
 return <div className="app">
  <header><div className="brand"><div className="mark">A</div><div><b>Asif's Security Studio</b><span>Interactive security knowledge workspace</span></div></div><div className="topsearch"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search commands, tools, techniques..."/></div><a className="notes" href="https://notes.asifnawazminhas.com/">Notes <ExternalLink size={14}/></a><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
  <aside className={mobile?'open':''}>{sections.map((s,i)=><div className="navgroup" key={i}>{s.title&&<label>{s.title}</label>}{s.items.map(([name,id,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={18}/>{name}</button>)}</div>)}<div className="sidefoot"><span className="dot"/> Studio v1.0</div></aside>
  <main>{page==='dashboard'?<Dashboard go={go}/>:page==='library'?<LibraryPage filtered={filtered} setSelected={setSelected} go={go}/>:page==='command-studio'?<CommandStudio command={selected}/>:page==='visualiser'?<Visualiser command={selected}/>:<Feature page={page}/>}</main>
 </div>
}
function Dashboard({go}){const quick=[['Command Library','library',Library,'Browse structured security commands'],['Command Studio','command-studio',TerminalSquare,'Explain, contextualise and copy commands'],['PrivEsc Explorer','privesc',ShieldCheck,'Explore privilege escalation checks'],['ATT&CK Explorer','attack',Network,'Map techniques to knowledge'],['Workflow Builder','workflow',Workflow,'Build reusable assessment flows'],['Purple Team Mapping','purple',Layers3,'Connect validation to defence']];return <><div className="hero"><div><span className="eyebrow">ASIF'S SECURITY STUDIO</span><h1>Security knowledge,<br/><em>made interactive.</em></h1><p>Explore commands, understand context, map telemetry and turn security notes into practical workflows.</p><div className="heroactions"><button onClick={()=>go('library')}>Explore Commands <ChevronRight size={16}/></button><a href="https://notes.asifnawazminhas.com/"><BookOpen size={16}/> Open Security Notes</a></div></div><div className="terminal"><div className="termbar"><i/><i/><i/><span>security-studio</span></div><code><b>$</b> knowledge --interactive<br/><span>✓ Commands indexed</span><br/><span>✓ ATT&CK mappings ready</span><br/><span>✓ Detection context loaded</span><br/><br/><b>$</b> explore <u>security</u><br/><strong>Ready.</strong></code></div></div><section><div className="sectionhead"><div><span className="eyebrow">WORKSPACE</span><h2>Choose where to start</h2></div></div><div className="grid">{quick.map(([n,id,I,d])=><button className="featurecard" onClick={()=>go(id)} key={id}><I/><div><h3>{n}</h3><p>{d}</p></div><ChevronRight className="arrow"/></button>)}</div></section><section><div className="banner"><Activity/><div><b>Built to connect Notes and Studio</b><span>Read the full methodology in Security Notes, then open interactive material here.</span></div></div></section></>}
function LibraryPage({filtered,setSelected,go}){return <><PageTitle kicker="COMMANDS" title="Command Library" text="Search structured commands by platform, tool and security context."/><div className="commandgrid">{filtered.map(c=><button className="commandcard" key={c.id} onClick={()=>{setSelected(c);go('command-studio')}}><div className="badges"><span>{c.platform}</span><span>{c.tool}</span></div><h3>{c.title}</h3><p>{c.desc}</p><code>{c.cmd}</code><div className="tags">{c.tags.map(t=><small key={t}>{t}</small>)}</div></button>)}</div></>}
function CommandStudio({command:c}){const copy=()=>navigator.clipboard?.writeText(c.cmd);return <><PageTitle kicker={`${c.platform} / ${c.category}`} title={c.title} text={c.desc}/><div className="studio"><div className="commandbox"><div><TerminalSquare size={18}/>{c.tool}</div><code>{c.cmd}</code><button onClick={copy}><Copy size={15}/> Copy</button></div><div className="tabs"><b>Explain</b><span>Modify</span><span>Detect</span><span>Visualise</span><span>Related</span></div><div className="twocol"><Panel title="Command Breakdown"><dl><dt>{c.cmd.split(' ')[0]}</dt><dd>Primary command or executable.</dd><dt>Arguments</dt><dd>{c.cmd.split(' ').slice(1).join(' ')||'No arguments'}</dd><dt>Category</dt><dd>{c.category}</dd></dl></Panel><Panel title="Command Context"><dl><dt>Platform</dt><dd>{c.platform}</dd><dt>Tool</dt><dd>{c.tool}</dd><dt>Changes system</dt><dd>No - reference entry</dd><dt>Purpose</dt><dd>{c.desc}</dd></dl></Panel></div><div className="threecol"><Panel title="Expected Output"><pre>{c.id==='applocker'?'<AppLockerPolicy Version="1">\n  <RuleCollection Type="Exe" ...>\n  ...\n</AppLockerPolicy>':'Output depends on the target environment.'}</pre></Panel><Panel title="Defender View"><p>Review process, script, operating-system and network telemetry relevant to this activity.</p><div className="status">● Detection context</div></Panel><Panel title="Related Knowledge"><p>Connect this command to the relevant Notes page, ATT&CK mapping and assessment workflow.</p><a href="https://notes.asifnawazminhas.com/">Open Notes <ExternalLink size={13}/></a></Panel></div></div></>}
function Visualiser({command:c}){return <><PageTitle kicker="COMMANDS" title="Command Visualiser" text="Create a clean, shareable command card with Security Studio branding."/><div className="visualwrap"><div className="preview"><div className="termbar"><i/><i/><i/><span>{c.tool}</span></div><code><b>{c.tool==='PowerShell'?'PS>':'$'}</b> {c.cmd}</code><small>studio.asifnawazminhas.com</small></div><Panel title="Visual settings"><p>Security Notes Dark</p><p>Terminal window</p><p>Watermark enabled</p><button className="primary">Export support - next phase</button></Panel></div></>}
function Feature({page}){const c=cards[page],I=c.icon;return <><PageTitle kicker="SECURITY STUDIO" title={c.title} text={c.desc}/><div className="coming"><I/><span>FOUNDATION MODULE</span><h2>{c.title}</h2><p>This module is scaffolded and ready for its interactive data and visual components.</p><div>{c.items.map(x=><span key={x}>✓ {x}</span>)}</div></div></>}
function PageTitle({kicker,title,text}){return <div className="pagetitle"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{text}</p></div>}
function Panel({title,children}){return <div className="panel"><h3>{title}</h3>{children}</div>}
createRoot(document.getElementById('root')).render(<App/>);
