import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Library,TerminalSquare,Image,ShieldCheck,Network,Workflow,RadioTower,GitCompareArrows,Search,Copy,ExternalLink,ChevronRight,Menu,X,BookOpen,Activity,Layers3,CheckCircle2,Filter,ArrowLeft,Download,Plus,Trash2} from 'lucide-react';
import {commands} from './data/commands';
import './styles.css';

const sections=[
 {title:'',items:[['Dashboard','dashboard',LayoutDashboard]]},
 {title:'COMMANDS',items:[['Command Library','library',Library],['Command Studio','command-studio',TerminalSquare],['Command Visualiser','visualiser',Image]]},
 {title:'EXPLORERS',items:[['PrivEsc Explorer','privesc',ShieldCheck],['ATT&CK Explorer','attack',Network],['Attack Path Explorer','attack-path',GitCompareArrows]]},
 {title:'BUILDERS',items:[['Workflow Builder','workflow',Workflow]]},
 {title:'DEFENCE',items:[['Detection & Telemetry','detection',RadioTower],['Purple Team Mapping','purple',Layers3]]}
];
const featureData={
 privesc:{title:'PrivEsc Explorer',desc:'Decision-support for reviewing privilege boundaries and defensive controls.',icon:ShieldCheck,steps:['Choose Windows or Linux','Review current identity and privileges','Check services, tasks and writable locations','Review application-control boundaries','Open the relevant Security Notes guidance']},
 'attack-path':{title:'Attack Path Explorer',desc:'Visualise identities, systems, permissions and security boundaries.',icon:GitCompareArrows,steps:['Identity','Group / role','Permission relationship','System','Control boundary']}
};
const attackCatalog=[
 {id:'T1082',name:'System Information Discovery',tactic:'Discovery'},
 {id:'T1016',name:'System Network Configuration Discovery',tactic:'Discovery'},
 {id:'T1046',name:'Network Service Discovery',tactic:'Discovery'},
 {id:'T1033',name:'System Owner/User Discovery',tactic:'Discovery'},
 {id:'T1049',name:'System Network Connections Discovery',tactic:'Discovery'},
 {id:'T1518.001',name:'Security Software Discovery',tactic:'Discovery'}
];
function App(){
 const [page,setPage]=useState('dashboard'),[query,setQuery]=useState(''),[platform,setPlatform]=useState('All'),[selected,setSelected]=useState(commands[0]),[mobile,setMobile]=useState(false),[tab,setTab]=useState('Explain');
 const go=p=>{setPage(p);setMobile(false);window.scrollTo(0,0)};
 const openCommand=c=>{setSelected(c);setTab('Explain');go('command-studio')};
 return <div className="app">
  <header><button className="brand" onClick={()=>go('dashboard')}><div className="mark">A</div><div><b>Asif's Security Studio</b><span>Interactive security knowledge workspace</span></div></button><div className="topsearch"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>page==='dashboard'&&go('library')} placeholder="Search commands, tools, techniques..."/><kbd>Ctrl K</kbd></div><a className="notes" href="https://notes.asifnawazminhas.com/">Notes <ExternalLink size={14}/></a><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
  <aside className={mobile?'open':''}>{sections.map((s,i)=><div className="navgroup" key={i}>{s.title&&<label>{s.title}</label>}{s.items.map(([name,id,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={18}/>{name}</button>)}</div>)}<div className="sidefoot"><span className="dot"/> Studio v1.1</div></aside>
  <main>{page==='dashboard'?<Dashboard go={go}/>:page==='library'?<LibraryPage query={query} setQuery={setQuery} platform={platform} setPlatform={setPlatform} openCommand={openCommand}/>:page==='command-studio'?<CommandStudio c={selected} tab={tab} setTab={setTab} go={go}/>:page==='visualiser'?<Visualiser c={selected}/>:page==='attack'?<AttackExplorer openCommand={openCommand}/>:page==='workflow'?<WorkflowBuilder/>:page==='detection'?<Detection/>:page==='purple'?<Purple/>:<Feature data={featureData[page]}/>}</main>
 </div>
}
function Dashboard({go}){const quick=[['Command Library','library',Library,'Search structured security commands'],['Command Studio','command-studio',TerminalSquare,'Explain, modify and contextualise commands'],['PrivEsc Explorer','privesc',ShieldCheck,'Explore privilege-boundary checks'],['ATT&CK Explorer','attack',Network,'Map techniques to commands and telemetry'],['Workflow Builder','workflow',Workflow,'Build reusable assessment flows'],['Purple Team Mapping','purple',Layers3,'Connect validation to defence']];return <><div className="hero"><div><span className="eyebrow">ASIF'S SECURITY STUDIO</span><h1>Security knowledge,<br/><em>made interactive.</em></h1><p>Explore commands, understand context, map telemetry and turn security notes into practical workflows.</p><div className="heroactions"><button onClick={()=>go('library')}>Explore Commands <ChevronRight size={16}/></button><a href="https://notes.asifnawazminhas.com/"><BookOpen size={16}/> Open Security Notes</a></div></div><div className="terminal"><div className="termbar"><i/><i/><i/><span>security-studio</span></div><code><b>$</b> knowledge --interactive<br/><span>✓ {commands.length} commands indexed</span><br/><span>✓ ATT&CK mappings loaded</span><br/><span>✓ Detection context ready</span><br/><br/><b>$</b> explore <u>security</u><br/><strong>Ready.</strong></code></div></div><section><div className="sectionhead"><div><span className="eyebrow">WORKSPACE</span><h2>Choose where to start</h2></div></div><div className="grid">{quick.map(([n,id,I,d])=><button className="featurecard" onClick={()=>go(id)} key={id}><I/><div><h3>{n}</h3><p>{d}</p></div><ChevronRight className="arrow"/></button>)}</div></section><section><div className="banner"><Activity/><div><b>Built to connect Notes and Studio</b><span>Read methodology in Security Notes, then explore structured interactive material here.</span></div></div></section></>}
function LibraryPage({query,setQuery,platform,setPlatform,openCommand}){const platforms=['All',...new Set(commands.map(c=>c.platform))];const filtered=useMemo(()=>commands.filter(c=>(platform==='All'||c.platform===platform)&&`${c.title} ${c.platform} ${c.tool} ${c.category} ${c.tags.join(' ')} ${c.command}`.toLowerCase().includes(query.toLowerCase())),[query,platform]);return <><PageTitle kicker="COMMANDS" title="Command Library" text="Search reusable security commands by platform, tool and security context."/><div className="librarytools"><div className="librarysearch"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search commands, tools, categories..."/></div><div className="filters"><Filter size={16}/>{platforms.map(p=><button className={platform===p?'selected':''} onClick={()=>setPlatform(p)} key={p}>{p}</button>)}</div></div><div className="resultline"><b>{filtered.length}</b> commands</div><div className="commandgrid">{filtered.map(c=><button className="commandcard" key={c.id} onClick={()=>openCommand(c)}><div className="badges"><span>{c.platform}</span><span>{c.tool}</span><small>{c.risk}</small></div><h3>{c.title}</h3><p>{c.description}</p><code>{c.command}</code><div className="tags">{c.tags.map(t=><small key={t}>{t}</small>)}</div><div className="openstudio">Open in Studio <ChevronRight size={15}/></div></button>)}</div>{!filtered.length&&<div className="empty">No commands match the current search and filters.</div>}</>}
function CommandStudio({c,tab,setTab,go}){const [values,setValues]=useState(Object.fromEntries(c.parameters.map(p=>[p.name,''])));const generated=c.parameters.reduce((s,p)=>s.replaceAll(`<${p.name}>`,values[p.name]||`<${p.name}>`),c.command);const copy=()=>navigator.clipboard?.writeText(generated);return <><button className="back" onClick={()=>go('library')}><ArrowLeft size={15}/> Command Library</button><PageTitle kicker={`${c.platform} / ${c.category}`} title={c.title} text={c.description}/><div className="studio"><div className="commandbox"><div><TerminalSquare size={18}/>{c.tool}<span>{c.risk}</span></div><code>{generated}</code><button onClick={copy}><Copy size={15}/> Copy</button></div><div className="tabs">{['Explain','Modify','Detect','Visualise','Related'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{tab==='Explain'&&<div className="twocol"><Panel title="Command Breakdown"><dl>{c.explanation.map(([a,b])=><React.Fragment key={a}><dt>{a}</dt><dd>{b}</dd></React.Fragment>)}</dl></Panel><Panel title="Context"><dl><dt>Platform</dt><dd>{c.platform}</dd><dt>Tool</dt><dd>{c.tool}</dd><dt>Category</dt><dd>{c.category}</dd><dt>Changes system</dt><dd>{c.changesSystem?'Yes':'No'}</dd></dl></Panel></div>}{tab==='Modify'&&<Panel title="Command Parameters">{c.parameters.length? <>{c.parameters.map(p=><label className="field" key={p.name}>{p.label}<input placeholder={p.placeholder} value={values[p.name]} onChange={e=>setValues({...values,[p.name]:e.target.value})}/></label>)}<div className="generated"><small>GENERATED COMMAND</small><code>{generated}</code><button onClick={copy}><Copy size={15}/> Copy</button></div></>:<p>This command has no editable placeholders.</p>}</Panel>}{tab==='Detect'&&<div className="twocol"><Panel title="Defender View"><p>Use the telemetry below as assessment context. A command alone is not automatically suspicious; correlation and intent matter.</p>{c.telemetry.map(x=><div className="check" key={x}><CheckCircle2 size={16}/>{x}</div>)}</Panel><Panel title="ATT&CK Context">{c.attack.length?c.attack.map(x=><div className="attackpill" key={x}>{x}</div>):<p>No ATT&CK mapping assigned to this reference entry.</p>}</Panel></div>}{tab==='Visualise'&&<VisualPreview c={{...c,command:generated}}/>}{tab==='Related'&&<div className="twocol"><Panel title="Security Notes"><p>Continue with the full methodology and supporting documentation.</p><a className="textlink" href={c.notes}>Open related Security Notes <ExternalLink size={14}/></a></Panel><Panel title="Tags"><div className="tags big">{c.tags.map(x=><small key={x}>{x}</small>)}</div></Panel></div>}</div></>}
function VisualPreview({c}){return <div className="preview large"><div className="termbar"><i/><i/><i/><span>{c.tool}</span></div><code><b>{c.tool==='PowerShell'?'PS>':'$'}</b> {c.command}</code><small>studio.asifnawazminhas.com</small></div>}
function Visualiser({c}){const [text,setText]=useState(c.command),[prompt,setPrompt]=useState(c.tool==='PowerShell'?'PS>':'$');return <><PageTitle kicker="COMMANDS" title="Command Visualiser" text="Create a clean Security Studio command card for documentation and sharing."/><div className="visualwrap"><div><VisualPreview c={{...c,command:text}}/></div><Panel title="Visual settings"><label className="field">Command<textarea value={text} onChange={e=>setText(e.target.value)}/></label><label className="field">Prompt<input value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><p className="muted">PNG/SVG export is reserved for the next release; the live preview is functional now.</p><button className="primary" onClick={()=>navigator.clipboard?.writeText(text)}><Copy size={15}/> Copy command</button></Panel></div></>}
function AttackExplorer({openCommand}){return <><PageTitle kicker="EXPLORERS" title="ATT&CK Explorer" text="Connect ATT&CK techniques to commands, defensive telemetry and Security Notes."/><div className="attackgrid">{attackCatalog.map(a=>{const mapped=commands.filter(c=>c.attack.includes(a.id));return <div className="attackcard" key={a.id}><div><span>{a.tactic}</span><b>{a.id}</b></div><h3>{a.name}</h3><p>{mapped.length} mapped command{mapped.length===1?'':'s'}</p>{mapped.map(c=><button key={c.id} onClick={()=>openCommand(c)}>{c.title}<ChevronRight size={14}/></button>)}</div>})}</div></>}
function WorkflowBuilder(){const [nodes,setNodes]=useState([{id:1,title:'Define scope'},{id:2,title:'Run validation'},{id:3,title:'Review telemetry'}]);return <><PageTitle kicker="BUILDERS" title="Workflow Builder" text="Arrange safe assessment and validation steps into a reusable visual workflow."/><div className="workflow"><div className="workflowbar"><button onClick={()=>setNodes([...nodes,{id:Date.now(),title:'New step'}])}><Plus size={15}/> Add step</button></div>{nodes.map((n,i)=><React.Fragment key={n.id}><div className="worknode"><span>{i+1}</span><input value={n.title} onChange={e=>setNodes(nodes.map(x=>x.id===n.id?{...x,title:e.target.value}:x))}/><button onClick={()=>setNodes(nodes.filter(x=>x.id!==n.id))}><Trash2 size={15}/></button></div>{i<nodes.length-1&&<div className="connector">↓</div>}</React.Fragment>)}</div></>}
function Detection(){const sources=['Process creation','PowerShell telemetry','Windows Event Logs','DNS telemetry','Web / proxy logs','Firewall / IDS','EDR telemetry'];return <><PageTitle kicker="DEFENCE" title="Detection & Telemetry" text="Explore which data sources provide visibility across the command catalogue."/><div className="metricgrid">{sources.map(s=>{const count=commands.filter(c=>c.telemetry.some(t=>t.toLowerCase().includes(s.split(' ')[0].toLowerCase()))).length;return <div className="metric" key={s}><RadioTower/><b>{count}</b><span>{s}</span></div>})}</div><Panel title="Telemetry coverage"><p>Open a command in Command Studio and select <b>Detect</b> to see its individual defensive context.</p></Panel></>}
function Purple(){return <><PageTitle kicker="DEFENCE" title="Purple Team Mapping" text="Connect validation actions to expected telemetry, detection and learning outcomes."/><div className="purpleflow">{['Validation action','Expected signal','Telemetry source','Detection','Response','Learning outcome'].map((x,i)=><React.Fragment key={x}><div><span>{i+1}</span><b>{x}</b><small>{['Authorised assessment step','What should become observable','Where the signal should appear','How the activity is identified','Expected defensive action','What should improve next'][i]}</small></div>{i<5&&<ChevronRight/>}</React.Fragment>)}</div><Panel title="How to use this mapping"><p>Start with an authorised validation objective, define the expected observable signal, identify the telemetry source, document detection behaviour and capture the resulting learning outcome.</p></Panel></>}
function Feature({data}){if(!data)return null;const I=data.icon;return <><PageTitle kicker="EXPLORERS" title={data.title} text={data.desc}/><div className="coming"><I/><span>INTERACTIVE FOUNDATION</span><h2>{data.title}</h2><p>This first release provides the structure for a decision-support explorer. The next dataset can connect each step directly to Security Notes.</p><div>{data.steps.map(x=><span key={x}>✓ {x}</span>)}</div></div></>}
function PageTitle({kicker,title,text}){return <div className="pagetitle"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{text}</p></div>}
function Panel({title,children}){return <div className="panel"><h3>{title}</h3>{children}</div>}
createRoot(document.getElementById('root')).render(<App/>);
